[general]
live_config_reload = true
working_directory = "C:/Users/hybl/"

[window]
dynamic_padding = true

[font]
normal = { family = "Lilex Nerd Font", style = "Regular" }
bold = { family = "Lilex Nerd Font", style = "Bold" }
italic = { family = "Lilex Nerd Font", style = "Italic" }
bold_italic = { family = "Lilex Nerd Font", style = "Bold Italic" }
size = 12

[terminal]
shell = "nu"

[mouse]
hide_when_typing = true

[colors.cursor]
text =   '#feffff'
cursor = '#ffb472'

[colors.primary]
foreground = "#CECDC3"
background = "#100F0F"
# foreground =        '#FFFCF0'
# background =        '#161616'
bright_foreground = '#FFFCF0'
dim_foreground =    '#FFFCF0'

[colors.normal]
black =   '#100F0F'
red =     '#D14D41'
green =   '#879A39'
yellow =  '#D0A215'
blue =    '#4385BE'
magenta = '#CE5D97'
cyan =    '#3AA99F'
white =   '#FFFCF0'

[colors.bright]
black =   '#575653'
red =     '#D14D41'
green =   '#879A39'
yellow =  '#D0A215'
blue =    '#4385BE'
magenta = '#8B7EC8'
cyan =    '#3AA99F'
white =   '#FFFCF0'

[colors.dim]
black =   '#100F0F'
red =     '#AF3029'
green =   '#66800B'
yellow =  '#AD8301'
blue =    '#205EA6'
magenta = '#5E409D'
cyan =    '#24837B'
white =   '#CECDC3'

[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
  { key = "T", mods = "Control|Shift", action = "CreateNewTab" },
]
