[helpers]

[default]
depends = []

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[default.variables]

[zed.files]
"zed-settings.json" = "~/.config/zed/settings.json"

[nu.files]
nushell = "~/.config/nushell"

[nvim.files]
nvim = "~/.config/nvim"

[alacritty.files]
"alacritty.toml" = "~/.config/alacritty.toml"

[settings]
default_target_type = "automatic"
