[helpers]

[default]
depends = ["starship"]

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[default.variables]

[zed.files]
"zed-settings.json" = "~/.config/zed/settings.json"

[nu.files]
nushell = "~/.config/nushell"

[nvim.files]
nvim = "~/.config/nvim"

[helix.files]
helix = "~/.config/helix"

[alacritty.files]
"alacritty.toml" = "~/.config/alacritty.toml"

[fonts.files.fonts]
"target" = "~/.local/share/fonts/"
"type" = "symbolic"

[settings]
default_target_type = "automatic"
