[helpers]

[default]
depends = [ ]

[default.files]
nvim = "~/.config/nvim"
nushell = "~/.config/nushell"
starship = "~/.config/starship.toml"

[default.variables]

[zed.files]
"zed-settings.json"= "~/.config/zed/settings.json"

[settings]
default_target_type = "automatic"
