[nvim.files]
nvim = "~/AppData/Local/nvim"

[zed.files]
"zed-settings.json" = "~/AppData/Roaming/Zed/settings.json"

[nu.files]
nushell = "~/AppData/Roaming/nushell"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[alacritty.files]
"alacritty.toml" = "~/AppData/Roaming/alacritty/alacritty.toml"
